# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://figur8s.github.io/kcherland.github.io/
title: Kelsey Cherland
email: kelsey.cherland@gmail.com
author: Kelsey Cherland
description: "Kelsey Cherland's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/figur8s 
  - icon: envelope-o
    title: email
    url: mailto:kelsey.cherland@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/kelsey-cherland/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/MyName

